//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.18 at 04:05:39 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://staub.spbspu.ru/Question", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.spbspu.staub.model.question;
