//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.29 at 11:16:16 AM MSK 
//


package ru.spbspu.staub.model.answer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for answer-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="answer-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="single-choice">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="element" type="{http://staub.spbspu.ru/Answer}element-type"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="multiple-choice">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="element" type="{http://staub.spbspu.ru/Answer}element-type" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "answer-type", propOrder = {
    "singleChoice",
    "multipleChoice"
})
public class AnswerType {

    @XmlElement(name = "single-choice")
    protected AnswerType.SingleChoice singleChoice;
    @XmlElement(name = "multiple-choice")
    protected AnswerType.MultipleChoice multipleChoice;

    /**
     * Gets the value of the singleChoice property.
     * 
     * @return
     *     possible object is
     *     {@link AnswerType.SingleChoice }
     *     
     */
    public AnswerType.SingleChoice getSingleChoice() {
        return singleChoice;
    }

    /**
     * Sets the value of the singleChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnswerType.SingleChoice }
     *     
     */
    public void setSingleChoice(AnswerType.SingleChoice value) {
        this.singleChoice = value;
    }

    /**
     * Gets the value of the multipleChoice property.
     * 
     * @return
     *     possible object is
     *     {@link AnswerType.MultipleChoice }
     *     
     */
    public AnswerType.MultipleChoice getMultipleChoice() {
        return multipleChoice;
    }

    /**
     * Sets the value of the multipleChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnswerType.MultipleChoice }
     *     
     */
    public void setMultipleChoice(AnswerType.MultipleChoice value) {
        this.multipleChoice = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="element" type="{http://staub.spbspu.ru/Answer}element-type" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "element"
    })
    public static class MultipleChoice {

        @XmlElement(required = true)
        protected List<ElementType> element;

        /**
         * Gets the value of the element property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the element property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ElementType }
         * 
         * 
         */
        public List<ElementType> getElement() {
            if (element == null) {
                element = new ArrayList<ElementType>();
            }
            return this.element;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="element" type="{http://staub.spbspu.ru/Answer}element-type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "element"
    })
    public static class SingleChoice {

        @XmlElement(required = true)
        protected ElementType element;

        /**
         * Gets the value of the element property.
         * 
         * @return
         *     possible object is
         *     {@link ElementType }
         *     
         */
        public ElementType getElement() {
            return element;
        }

        /**
         * Sets the value of the element property.
         * 
         * @param value
         *     allowed object is
         *     {@link ElementType }
         *     
         */
        public void setElement(ElementType value) {
            this.element = value;
        }

    }

}
