//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 05:55:43 PM MSK 
//


package ru.spbspu.staub.model.answer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.spbspu.staub.model.answer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Answer_QNAME = new QName("http://staub.spbspu.ru/Answer", "answer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.spbspu.staub.model.answer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ElementType }
     * 
     */
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link AnswerType }
     * 
     */
    public AnswerType createAnswerType() {
        return new AnswerType();
    }

    /**
     * Create an instance of {@link AnswerType.SingleChoice }
     * 
     */
    public AnswerType.SingleChoice createAnswerTypeSingleChoice() {
        return new AnswerType.SingleChoice();
    }

    /**
     * Create an instance of {@link AnswerType.MultipleChoice }
     * 
     */
    public AnswerType.MultipleChoice createAnswerTypeMultipleChoice() {
        return new AnswerType.MultipleChoice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnswerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://staub.spbspu.ru/Answer", name = "answer")
    public JAXBElement<AnswerType> createAnswer(AnswerType value) {
        return new JAXBElement<AnswerType>(_Answer_QNAME, AnswerType.class, null, value);
    }

}
